version: "3.9"

services:
  api:
    build: .
    container_name: node_api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:16
    container_name: fastmeals
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
